# Generated by Django 5.1.4 on 2025-04-09 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherpay',
            name='type',
        ),
        migrations.AddField(
            model_name='driver',
            name='user_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='load',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherpay',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('DETENTION', 'Detention'), ('EQUIPMENT', 'Equipment'), ('LAYOVER', 'Layover'), ('LUMPER', 'Lumper'), ('DRIVERASSISTANCE', 'Driver Assistance'), ('TRAILERWASH', 'Trailer Wash'), ('EXCORTFEE', 'Excort Fee'), ('BONUS', 'Bonus'), ('CHARGEBAG', 'Charge Bag'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher', to='apps_load.dispatcher'),
        ),
        migrations.AlterField(
            model_name='load',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='load_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('COVERED', 'Covered'), ('DISPATCHED', 'Dispatched'), ('LOADING', 'Loading'), ('ON_ROUTE', 'On Route'), ('UNLOADING', 'Unloading'), ('IN_YARD', 'In Yard'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otherpay',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherpay_load', to='apps_load.load'),
        ),
        migrations.AlterField(
            model_name='otherpay',
            name='pay',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DriverExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('+', 'Income'), ('-', 'Expense')], max_length=1)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='apps_load.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Per Mile', 'Per Mile'), ('Hourly', 'Hourly')], max_length=50, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('CAD', 'CAD')], max_length=50, null=True)),
                ('standart', models.FloatField(blank=True, null=True)),
                ('additional_charges', models.FloatField(blank=True, null=True)),
                ('picks_per', models.IntegerField(blank=True, null=True)),
                ('drops_per', models.IntegerField(blank=True, null=True)),
                ('wait_time', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_pay_amount', to='apps_load.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_from', models.DateField(blank=True, null=True)),
                ('pay_to', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='driver_pay_files/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('loads', models.JSONField(blank=True, default=list, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_pay', to='apps_load.driver')),
                ('pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_driver', to='apps_load.pay')),
            ],
        ),
    ]
