# Generated by Django 5.1.4 on 2025-04-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0002_remove_otherpay_type_driver_user_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='escrow_deposit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
