# Generated by Django 5.1.4 on 2025-04-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0003_driver_escrow_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherpay',
            name='pay',
        ),
    ]
