# Generated by Django 5.1.4 on 2025-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0004_remove_otherpay_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='motive_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otherpay',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('DETENTION', 'Detention'), ('EQUIPMENT', 'Equipment'), ('LAYOVER', 'Layover'), ('LUMPER', 'Lumper'), ('DRIVERASSIST', 'Driver Assist'), ('TRAILERWASH', 'Trailer Wash'), ('ESCORTFEE', 'Escort Fee'), ('BONUS', 'Bonus'), ('CHARGEBACK', 'Charge Back'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
    ]
