# Generated by Django 5.1.4 on 2025-04-16 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0006_load_driver_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatcher',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='password',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user_admin',
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
