# Generated by Django 5.1.4 on 2025-04-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0010_alter_load_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatcher',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='state',
        ),
        migrations.RemoveField(
            model_name='dispatcher',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='country',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='state',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='zip_code',
        ),
    ]
