# Generated by Django 5.1.4 on 2025-04-24 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0011_remove_dispatcher_address1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(unique=True)),
                ('dispatcher', models.ManyToManyField(blank=True, null=True, related_name='dispatchers', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ManyToManyField(blank=True, null=True, related_name='drivers', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ManyToManyField(blank=True, null=True, related_name='employees', to='apps_load.employee')),
                ('trailer', models.ManyToManyField(blank=True, null=True, related_name='trailers', to='apps_load.trailer')),
                ('truck', models.ManyToManyField(blank=True, null=True, related_name='units', to='apps_load.truck')),
            ],
        ),
    ]
