# Generated by Django 5.2 on 2025-04-26 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0012_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
