# Generated by Django 5.2 on 2025-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0014_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='dispatcher',
            field=models.ManyToManyField(blank=True, null=True, related_name='dispatchers', to='apps_load.dispatcher'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='driver',
            field=models.ManyToManyField(blank=True, null=True, related_name='drivers', to='apps_load.driver'),
        ),
    ]
