# Generated by Django 5.2 on 2025-04-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0015_alter_unit_dispatcher_alter_unit_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='dispatcher',
            field=models.ManyToManyField(blank=True, null=True, related_name='unit_dispatchers', to='apps_load.dispatcher'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='driver',
            field=models.ManyToManyField(blank=True, null=True, related_name='unit_drivers', to='apps_load.driver'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, related_name='unit_employees', to='apps_load.employee'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='trailer',
            field=models.ManyToManyField(blank=True, null=True, related_name='unit_trailers', to='apps_load.trailer'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='truck',
            field=models.ManyToManyField(blank=True, null=True, related_name='unit_trucks', to='apps_load.truck'),
        ),
    ]
