# Generated by Django 5.2 on 2025-04-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0017_load_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='stop',
        ),
        migrations.AddField(
            model_name='load',
            name='stop',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_loads', to='apps_load.stops'),
        ),
    ]
