# Generated by Django 5.2 on 2025-04-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0018_remove_load_stop_load_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='stop',
            field=models.ManyToManyField(null=True, related_name='related_loads', to='apps_load.stops'),
        ),
    ]
