# Generated by Django 5.2 on 2025-04-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0020_alter_load_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='group_message_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
