# Generated by Django 5.2 on 2025-04-30 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0021_load_group_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='appointmentdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]