# Generated by Django 5.2 on 2025-04-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0023_rename_created_date_load_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
