# Generated by Django 5.2 on 2025-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0024_alter_load_created_at_alter_load_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
