# Generated by Django 5.2 on 2025-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0025_alter_load_created_at_alter_load_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='appointmentdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
