# Generated by Django 5.2 on 2025-04-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0026_alter_stops_appointmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_load', to='apps_load.unit'),
        ),
    ]
