# Generated by Django 5.2 on 2025-04-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0027_load_unit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
