# Generated by Django 5.2 on 2025-04-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0028_rename_created_at_load_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stops',
            name='time',
        ),
    ]
