# Generated by Django 5.2 on 2025-04-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0029_remove_stops_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='fcfs',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='plus_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
