# Generated by Django 5.2 on 2025-04-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0030_stops_fcfs_stops_plus_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
