# Generated by Django 5.2 on 2025-04-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0031_alter_stops_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='stop_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
