# Generated by Django 5.2 on 2025-05-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0032_alter_stops_stop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='dispatcher',
        ),
        migrations.AlterField(
            model_name='stops',
            name='plus_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
