# Generated by Django 5.2 on 2025-05-01 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0033_remove_unit_dispatcher_alter_stops_plus_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telegram_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatchers', models.ManyToManyField(blank=True, related_name='dispatchers', to='apps_load.dispatcher')),
                ('unit_id', models.ManyToManyField(blank=True, related_name='unit_id', to='apps_load.unit')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_team_id', to='apps_load.team'),
        ),
    ]
