# Generated by Django 5.2 on 2025-05-01 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0034_team_unit_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_load', to='apps_load.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
