# Generated by Django 5.2 on 2025-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0035_load_team_id_team_telegram_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(unique=True),
        ),
    ]
