# Generated by Django 5.2 on 2025-05-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0036_alter_unit_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='unit_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='unit_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
