# Generated by Django 5.2 on 2025-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0037_alter_trailer_unit_number_alter_truck_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbroker',
            name='contact_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
