# Generated by Django 5.2 on 2025-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0038_alter_customerbroker_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverexpense',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverexpense',
            name='weekly_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverpay',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverpay',
            name='weekly_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
