# Generated by Django 5.2 on 2025-07-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0039_driverexpense_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpay',
            name='cd_file',
            field=models.FileField(blank=True, null=True, upload_to='driver_pay_cd_files/'),
        ),
    ]
