# Generated by Django 5.2 on 2025-07-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0042_amazonrelaypayment_load_amazon_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmazonRelayPayment',
        ),
    ]
