# Generated by Django 5.2 on 2025-07-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0044_amazonrelaypayment_amazonrelayprocessedrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonrelayprocessedrecord',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='amazonrelayprocessedrecord',
            name='matched_load',
        ),
        migrations.DeleteModel(
            name='AmazonRelayPayment',
        ),
        migrations.DeleteModel(
            name='AmazonRelayProcessedRecord',
        ),
    ]
