# Generated by Django 5.2 on 2025-07-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0046_amazonrelaypayment_amazonrelayprocessedrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonrelaypayment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazonrelaypayment',
            name='weekly_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazonrelaypayment',
            name='work_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonrelaypayment',
            name='work_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='weekly_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
