# Generated by Django 5.2 on 2025-07-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0047_amazonrelaypayment_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv_imports/')),
                ('start_row', models.IntegerField(default=2, help_text='Qaysi qatordan boshlash (Excel formatida, masalan 2)')),
                ('end_row', models.IntegerField(help_text='Qaysi qatorgacha (Excel formatida, masalan 2200)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CSV Import',
                'verbose_name_plural': 'CSV Imports',
            },
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_name',
            field=models.CharField(blank=True, choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery'), ('Stop-2', 'Stop-2'), ('Stop-3', 'Stop-3')], max_length=20, null=True),
        ),
    ]
