# Generated by Django 5.2 on 2025-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_load', '0048_csvimport_alter_stops_stop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimport',
            name='csv_file',
            field=models.FileField(upload_to='amazon_relay_files/'),
        ),
    ]
