# Generated by Django 5.1.4 on 2025-04-17 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0005_alter_user_role_company_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('load_create', models.BooleanField(default=False)),
                ('load_update', models.BooleanField(default=False)),
                ('load_delete', models.BooleanField(default=False)),
                ('load_view', models.BooleanField(default=False)),
                ('driver_create', models.BooleanField(default=False)),
                ('driver_update', models.BooleanField(default=False)),
                ('driver_delete', models.BooleanField(default=False)),
                ('driver_view', models.BooleanField(default=False)),
                ('truck_create', models.BooleanField(default=False)),
                ('truck_update', models.BooleanField(default=False)),
                ('truck_delete', models.BooleanField(default=False)),
                ('truck_view', models.BooleanField(default=False)),
                ('trailer_create', models.BooleanField(default=False)),
                ('trailer_update', models.BooleanField(default=False)),
                ('trailer_delete', models.BooleanField(default=False)),
                ('trailer_view', models.BooleanField(default=False)),
                ('user_create', models.BooleanField(default=False)),
                ('user_update', models.BooleanField(default=False)),
                ('user_delete', models.BooleanField(default=False)),
                ('user_view', models.BooleanField(default=False)),
                ('accounting_create', models.BooleanField(default=False)),
                ('accounting_update', models.BooleanField(default=False)),
                ('accounting_delete', models.BooleanField(default=False)),
                ('accounting_view', models.BooleanField(default=False)),
                ('dispatcher_create', models.BooleanField(default=False)),
                ('dispatcher_update', models.BooleanField(default=False)),
                ('dispatcher_delete', models.BooleanField(default=False)),
                ('dispatcher_view', models.BooleanField(default=False)),
                ('stop_create', models.BooleanField(default=False)),
                ('stop_update', models.BooleanField(default=False)),
                ('stop_delete', models.BooleanField(default=False)),
                ('stop_view', models.BooleanField(default=False)),
                ('otherpay_create', models.BooleanField(default=False)),
                ('otherpay_update', models.BooleanField(default=False)),
                ('otherpay_delete', models.BooleanField(default=False)),
                ('otherpay_view', models.BooleanField(default=False)),
                ('employee_create', models.BooleanField(default=False)),
                ('employee_update', models.BooleanField(default=False)),
                ('employee_delete', models.BooleanField(default=False)),
                ('employee_view', models.BooleanField(default=False)),
                ('commodity_create', models.BooleanField(default=False)),
                ('commodity_update', models.BooleanField(default=False)),
                ('commodity_delete', models.BooleanField(default=False)),
                ('commodity_view', models.BooleanField(default=False)),
                ('customerbroker_create', models.BooleanField(default=False)),
                ('customerbroker_update', models.BooleanField(default=False)),
                ('customerbroker_delete', models.BooleanField(default=False)),
                ('customerbroker_view', models.BooleanField(default=False)),
                ('chat_create', models.BooleanField(default=False)),
                ('chat_update', models.BooleanField(default=False)),
                ('chat_delete', models.BooleanField(default=False)),
                ('chat_view', models.BooleanField(default=False)),
                ('userlocation_create', models.BooleanField(default=False)),
                ('userlocation_update', models.BooleanField(default=False)),
                ('userlocation_delete', models.BooleanField(default=False)),
                ('userlocation_view', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='apps_auth.permission')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='apps_auth.role'),
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('page_status', models.CharField(choices=[('open', 'Open'), ('hidden', 'Hidden')], default='open', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
