# Generated by Django 5.1.4 on 2025-04-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0006_permission_remove_user_callphone_user_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='callphone',
        ),
    ]
