# Generated by Django 5.1.4 on 2025-04-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0007_remove_user_callphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
