# Generated by Django 5.1.4 on 2025-04-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0009_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='media/profile/profile_avatar.png', null=True, upload_to='media/profile'),
        ),
    ]
