# Generated by Django 5.2 on 2025-04-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0010_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
