# Generated by Django 5.2 on 2025-04-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0013_merge_20250424_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, default='media/profile/profile_avatar.jpg', null=True, upload_to='media/profile'),
        ),
    ]
