# Generated by Django 5.1.4 on 2025-03-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_load', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('load_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoadChat', to='apps_load.load')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserChat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
