# Generated by Django 5.1.4 on 2025-03-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_chat', '0002_chat_file_alter_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='file',
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
