# Generated by Django 5.1.4 on 2025-03-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_chat', '0007_remove_chat_file_alter_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='chat',
            name='group_message_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
